CREATE TABLE FEED_CATEGORY (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME NVARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE FEED (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME NVARCHAR(255) NOT NULL,
    ADDRESS NVARCHAR(2048) NOT NULL,
    CATEGORY_ID INT NOT NULL,
    CONSTRAINT CONSTRAINT_FEED_CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES FEED_CATEGORY,
    PRIMARY KEY(ID)
);

CREATE TABLE APP_ROLE (
    ID INT NOT NULL AUTO_INCREMENT,
    DESCRIPTION NVARCHAR(255) NOT NULL,
    ROLE_NAME NVARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE APP_USER (
    ID INT NOT NULL AUTO_INCREMENT,
    USERNAME NVARCHAR(255) NOT NULL,
    PASSWORD NVARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLE (
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    CONSTRAINT USER_ROLE_USER_FK FOREIGN KEY (USER_ID) REFERENCES APP_USER (ID),
    CONSTRAINT USER_ROLE_ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES APP_ROLE (ID)
);

