INSERT INTO APP_ROLE (ID, DESCRIPTION, ROLE_NAME) VALUES (1, 'Regular User', 'USER');
INSERT INTO APP_ROLE (ID, DESCRIPTION, ROLE_NAME) VALUES (2, 'Admin User', 'ADMIN');

-- Password is 'password'
INSERT INTO APP_USER (ID, USERNAME, PASSWORD) VALUES (1, 'Bora', '$2a$09$uf3HlfTXYL.FYQbi98Y3oOCSgGg3Pyn98UUS3xIqJPWXtE9/Mp0we');
INSERT INTO APP_USER (ID, USERNAME, PASSWORD) VALUES (2, 'Admin', '$2a$09$uf3HlfTXYL.FYQbi98Y3oOCSgGg3Pyn98UUS3xIqJPWXtE9/Mp0we');

INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES (1,1);
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES (2,1);
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES (2,2);

INSERT INTO FEED_CATEGORY(ID, NAME) VALUES (1, 'News Stories');
INSERT INTO FEED_CATEGORY(ID, NAME) VALUES (2, 'Tech related');
INSERT INTO FEED_CATEGORY(ID, NAME) VALUES (3, 'Time wasters');

INSERT INTO FEED (ID, NAME, ADDRESS, CATEGORY_ID) VALUES (1, 'Google News', '', 1);
INSERT INTO FEED (ID, NAME, ADDRESS, CATEGORY_ID) VALUES (2, 'Hacker News', '', 2);
INSERT INTO FEED (ID, NAME, ADDRESS, CATEGORY_ID) VALUES (3, 'Reddit', '', 3);


